import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ticketing System</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      
        <div className='container border-2 border-black-100 rounded-xl mt-8 w-2/3 m-auto  bg-slate-200 '>
          <h1 className='m-2 text-center font-bold text-xl'>About us</h1>
          <p className='m-2 '>Since there are a lot of scams in the ticket resale industry, we have come up with a solution to make the ticketing decentralized by using the blockhain. Each person who buys a ticket will own a NFT and cannot re-
          sell the ticket for a higher price. This platform acts like a marketplace for events that run in huge scale</p>
        </div>
        
    </div>
  )
}
