import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ticketing System</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='container border-2 border-black-100 rounded-2xl mt-10 w-2/3 m-auto  bg-slate-200 '>
        <h1 className='m-2 text-center text-[50px] text-xl font-bold mt-6 mb-10'>
          About us
        </h1>
        <p className='m-2 text-[25px] mr-4 ml-4 text-left '>
          As a blockchain-ticketing-system company, we offer a secure and
          efficient solution for the sale and distribution of tickets. Our
          system utilizes blockchain technology, which ensures that each ticket
          is unique and cannot be counterfeited. Our platform offers several
          benefits for both event organizers and attendees. For organizers, our
          system allows for the seamless and secure sale of tickets, eliminating
          the need for paper tickets and reducing the risk of fraud. It also
          enables real-time tracking of ticket sales and attendee information,
          allowing for better event planning and management. For attendees, our
          platform offers a user-friendly and convenient way to purchase and
          manage tickets. They can easily access their tickets on their mobile
          devices and transfer them to others if needed. Overall, our
          blockchain-based ticketing system offers enhanced security,
          transparency, and convenience for all stakeholders involved in the
          event industry.
        </p>
        <p className='m-2 text-[25px] mr-4 ml-4 text-left '>
          Additionally, our platform offers a number of other benefits,
          including: Increased security: By using blockchain technology, we can
          provide a secure and tamper-proof record of ticket ownership and
          sales. This makes it virtually impossible for tickets to be stolen or
          counterfeited. Improved accessibility: Our platform allows users to
          easily purchase and transfer tickets through their mobile devices,
          making it easier and more convenient for fans to attend events.
          Enhanced transparency: With our platform, event organizers and fans
          can see a complete history of ticket sales, including the original
          owner and any subsequent transfers. This allows for greater
          transparency and accountability in the ticketing process. Overall, our
          blockchain-based ticketing system offers a secure, transparent, and
          accessible solution for event organizers and fans alike. By
          eliminating the black market and protecting the rights of all parties
          involved, we are able to provide a better, more trustworthy ticketing
          experience for everyone.
        </p>
      </div>
    </div>
  )
}
